{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kord-core/0.15.0-SNAPSHOT/kord-core-0.15.0-SNAPSHOT.module",
    "group": "dev.kord",
    "module": "kord-core",
    "version": "0.15.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.kord",
          "module": "kord-common",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-rest",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-gateway",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord.cache",
          "module": "cache-api",
          "version": {
            "requires": "0.5.4"
          }
        },
        {
          "group": "dev.kord.cache",
          "module": "cache-map",
          "version": {
            "requires": "0.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm.jar",
          "url": "kord-core-jvm-0.15.0-SNAPSHOT.jar",
          "size": 4705293,
          "sha512": "b16cdcf4af28f32533627c255097d348b9095d42b90f73a3a53e03c70004ade86db0d97cc92e18e1ffc19a5a4a0e62735b395c88d2e85dc151d2462788f510b8",
          "sha256": "1321f95799162a57b66bd21c401a501ad1cecd4ba70d81836075f58e141f7728",
          "sha1": "31f544eb82d1049cf4510f0722b49b5abebad2f9",
          "md5": "b22fc3e4fdc112398a5195842dc5fd63"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.kord",
          "module": "kord-common",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-rest",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-gateway",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord.cache",
          "module": "cache-api",
          "version": {
            "requires": "0.5.4"
          }
        },
        {
          "group": "dev.kord.cache",
          "module": "cache-map",
          "version": {
            "requires": "0.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "3.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm.jar",
          "url": "kord-core-jvm-0.15.0-SNAPSHOT.jar",
          "size": 4705293,
          "sha512": "b16cdcf4af28f32533627c255097d348b9095d42b90f73a3a53e03c70004ade86db0d97cc92e18e1ffc19a5a4a0e62735b395c88d2e85dc151d2462788f510b8",
          "sha256": "1321f95799162a57b66bd21c401a501ad1cecd4ba70d81836075f58e141f7728",
          "sha1": "31f544eb82d1049cf4510f0722b49b5abebad2f9",
          "md5": "b22fc3e4fdc112398a5195842dc5fd63"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "core-jvm-sources.jar",
          "url": "kord-core-jvm-0.15.0-SNAPSHOT-sources.jar",
          "size": 329738,
          "sha512": "e391aaf579d4cd09d71e12ec4e25f9cb70ec9782b163092c7edd21c9f81d9a4e7e17123e44f6d17b251a90a069b3d4a48900fcb9bf740c2b2aa17cad244d879f",
          "sha256": "33c085e004339d27421abd2f722653a82d7cd57db6a748231fce8b28d4bf1232",
          "sha1": "c828f7d3377011f527fff6283a98b933276c671b",
          "md5": "e796914a6624b364cbc7f02220393892"
        }
      ]
    }
  ]
}
