{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kord-core/0.15.0-SNAPSHOT/kord-core-0.15.0-SNAPSHOT.module",
    "group": "dev.kord",
    "module": "kord-core",
    "version": "0.15.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-common",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-rest",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-gateway",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord.cache",
          "module": "cache-api",
          "version": {
            "requires": "0.5.4"
          }
        },
        {
          "group": "dev.kord.cache",
          "module": "cache-map",
          "version": {
            "requires": "0.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-js.klib",
          "url": "kord-core-js-0.15.0-SNAPSHOT.klib",
          "size": 1966262,
          "sha512": "320f8d3bbae18a1c9000a9577568af0a781a033a42fecbac663e3bc735e89dd199016069f97eb7b4f019e296ecfadd0578d1d6fc3b6c6f68ef95e89589812857",
          "sha256": "39f92c85f4013b167945e003f51c324990a571f6563fae0474684aaa4741ecc1",
          "sha1": "17f35e1e69fa5d5dda150ae583631dedefeccef5",
          "md5": "463e695a8f69b9d66190836766d395bf"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlinx-atomicfu-runtime",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-common",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-rest",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-gateway",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord.cache",
          "module": "cache-api",
          "version": {
            "requires": "0.5.4"
          }
        },
        {
          "group": "dev.kord.cache",
          "module": "cache-map",
          "version": {
            "requires": "0.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "3.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "core-js.klib",
          "url": "kord-core-js-0.15.0-SNAPSHOT.klib",
          "size": 1966262,
          "sha512": "320f8d3bbae18a1c9000a9577568af0a781a033a42fecbac663e3bc735e89dd199016069f97eb7b4f019e296ecfadd0578d1d6fc3b6c6f68ef95e89589812857",
          "sha256": "39f92c85f4013b167945e003f51c324990a571f6563fae0474684aaa4741ecc1",
          "sha1": "17f35e1e69fa5d5dda150ae583631dedefeccef5",
          "md5": "463e695a8f69b9d66190836766d395bf"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "core-js-sources.jar",
          "url": "kord-core-js-0.15.0-SNAPSHOT-sources.jar",
          "size": 328164,
          "sha512": "b517e7e75b1df4e9bd0dc2d865efa2d66f63877ecd2aad21cc53ef59006d79557d2f96ee580baeeb6b2811a017a8f5ac3550b3e75de83bcf695e9918a9a81cfc",
          "sha256": "52a0c3f227127da1e96ee9c6e2260474623f69549bb1d1ac8325530a775c38e8",
          "sha1": "99adcef5e97a769560c4d9bbbb8ea08b5ac5e76c",
          "md5": "40ddfcafdf2a2132da7da8ff502d1b7a"
        }
      ]
    }
  ]
}
