{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kord-rest/new-voice-encryption-modes-SNAPSHOT/kord-rest-new-voice-encryption-modes-SNAPSHOT.module",
    "group": "dev.kord",
    "module": "kord-rest",
    "version": "new-voice-encryption-modes-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-common",
          "version": {
            "requires": "new-voice-encryption-modes-SNAPSHOT"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "rest-js.klib",
          "url": "kord-rest-js-new-voice-encryption-modes-SNAPSHOT.klib",
          "size": 1101166,
          "sha512": "bdf1740aba2288f32397cc9102753e9a9ba866858ca6e0b6faa78514b37e071b8bac0087546f2ab0c9e3cc06072c7d5723adc06cccea4855349ab7942a267a40",
          "sha256": "afb73333cb7ec5882445b275fbaf33f462d70a9cf82fc49a42655162c80298ba",
          "sha1": "fe3b7d630c16d61c196d408b38d5843989b72352",
          "md5": "6d022ee028db9c7af7d616cbab51f376"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlinx-atomicfu-runtime",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-common",
          "version": {
            "requires": "new-voice-encryption-modes-SNAPSHOT"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "rest-js.klib",
          "url": "kord-rest-js-new-voice-encryption-modes-SNAPSHOT.klib",
          "size": 1101166,
          "sha512": "bdf1740aba2288f32397cc9102753e9a9ba866858ca6e0b6faa78514b37e071b8bac0087546f2ab0c9e3cc06072c7d5723adc06cccea4855349ab7942a267a40",
          "sha256": "afb73333cb7ec5882445b275fbaf33f462d70a9cf82fc49a42655162c80298ba",
          "sha1": "fe3b7d630c16d61c196d408b38d5843989b72352",
          "md5": "6d022ee028db9c7af7d616cbab51f376"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "rest-js-sources.jar",
          "url": "kord-rest-js-new-voice-encryption-modes-SNAPSHOT-sources.jar",
          "size": 142170,
          "sha512": "19f24089170bebb0dd4afabe9430d59111360be6c6477dc0a1e838f2b5970566e8f2c67e204312d15c49f258a77cb179325660e8b67f184e824063ccc269b36c",
          "sha256": "891cf487eac0d36b7dc4a036967681c5bc2b1f8836f7e7b05ddb477133affc16",
          "sha1": "461a4da4944a6e6f5e5b62f5fc992b2f971816ed",
          "md5": "4cbe6c9ab75628437d62f3f5f4794f18"
        }
      ]
    }
  ]
}
