{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kord-rest/new-voice-encryption-modes-0170-SNAPSHOT/kord-rest-new-voice-encryption-modes-0170-SNAPSHOT.module",
    "group": "dev.kord",
    "module": "kord-rest",
    "version": "new-voice-encryption-modes-0170-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.29.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-common",
          "version": {
            "requires": "new-voice-encryption-modes-0170-SNAPSHOT"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "rest-js.klib",
          "url": "kord-rest-js-new-voice-encryption-modes-0170-SNAPSHOT.klib",
          "size": 1130491,
          "sha512": "cc6bad0f77c9393f1cfd117f9f237fc0f1a6092f7f8567f0fad7b57404f7df650ff30dc3d82aa2b31fea632317367064187eef2e9bfb6d00425f659a8bd56828",
          "sha256": "5ba77b54748811a5543fadca1097991e6508500d10d37c47f8f5986d16360016",
          "sha1": "633a8cab894f30b4595d9a47fc85113cb43841cd",
          "md5": "30e279ce6e03a287d17a4296ffa3b459"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlinx-atomicfu-runtime",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.29.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-common",
          "version": {
            "requires": "new-voice-encryption-modes-0170-SNAPSHOT"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "rest-js.klib",
          "url": "kord-rest-js-new-voice-encryption-modes-0170-SNAPSHOT.klib",
          "size": 1130491,
          "sha512": "cc6bad0f77c9393f1cfd117f9f237fc0f1a6092f7f8567f0fad7b57404f7df650ff30dc3d82aa2b31fea632317367064187eef2e9bfb6d00425f659a8bd56828",
          "sha256": "5ba77b54748811a5543fadca1097991e6508500d10d37c47f8f5986d16360016",
          "sha1": "633a8cab894f30b4595d9a47fc85113cb43841cd",
          "md5": "30e279ce6e03a287d17a4296ffa3b459"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "rest-js-sources.jar",
          "url": "kord-rest-js-new-voice-encryption-modes-0170-SNAPSHOT-sources.jar",
          "size": 154257,
          "sha512": "2206774ab7449bde5bc88cbe0e302ab76b65fa64d05139124a42fc901dce9b77e249f6843799cd8faebd0c48bccf04e99bcbb046abeb095c50fda60d0df957ea",
          "sha256": "aac8e61947bc464fb2af28a3fdbcbc8a17e09a66b5e8804aff0716d2232f73ff",
          "sha1": "2bb460dd8d816302d887f9d65ca8afefaff2d47d",
          "md5": "8f7059350fa570ba6937849ac580c08f"
        }
      ]
    }
  ]
}
