{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.kord",
    "module": "kord-ksp-annotations",
    "version": "new-voice-encryption-modes-0170-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "ksp-annotations-metadata.jar",
          "url": "kord-ksp-annotations-new-voice-encryption-modes-0170-SNAPSHOT.jar",
          "size": 2641,
          "sha512": "e0ae6f3914fcd7e78bd16dbc978a303c4e43aaa7956c2d741924a1674d1fb3ae7b3994dc1390f922b40acd1e6d055b6f3535e16e4fba5ab630652e504d8b0eb5",
          "sha256": "947ccd1766d6415b63a92bed70001f8f614d4c0a3e46e990d436df81fca8239b",
          "sha1": "b9a40cac12168c1b9456a8ac949bd60601f6a83f",
          "md5": "c248cda183cc8d8732c39b33481ff6a8"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ksp-annotations-kotlin-sources.jar",
          "url": "kord-ksp-annotations-new-voice-encryption-modes-0170-SNAPSHOT-sources.jar",
          "size": 1200,
          "sha512": "34642383e14d027a42da882a85e02f0ac6742b49dc4b290389f9ef6840dc72c69b472e5a624d2a465f84b36c96665d676dbdfc04a4b7ca4d1085f7a1affdfe0b",
          "sha256": "0c176462e51edf8ae8369e6db0f2d2b3c9dcbe1eb1a5f98e6433b3674e4a9daa",
          "sha1": "2fdf65336269ad40e4bc74778b6d8fbdc558326a",
          "md5": "c098039c227b6feb99a7cd3434b7eacf"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kord-ksp-annotations-js/new-voice-encryption-modes-0170-SNAPSHOT/kord-ksp-annotations-js-new-voice-encryption-modes-0170-SNAPSHOT.module",
        "group": "dev.kord",
        "module": "kord-ksp-annotations-js",
        "version": "new-voice-encryption-modes-0170-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kord-ksp-annotations-js/new-voice-encryption-modes-0170-SNAPSHOT/kord-ksp-annotations-js-new-voice-encryption-modes-0170-SNAPSHOT.module",
        "group": "dev.kord",
        "module": "kord-ksp-annotations-js",
        "version": "new-voice-encryption-modes-0170-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kord-ksp-annotations-js/new-voice-encryption-modes-0170-SNAPSHOT/kord-ksp-annotations-js-new-voice-encryption-modes-0170-SNAPSHOT.module",
        "group": "dev.kord",
        "module": "kord-ksp-annotations-js",
        "version": "new-voice-encryption-modes-0170-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kord-ksp-annotations-jvm/new-voice-encryption-modes-0170-SNAPSHOT/kord-ksp-annotations-jvm-new-voice-encryption-modes-0170-SNAPSHOT.module",
        "group": "dev.kord",
        "module": "kord-ksp-annotations-jvm",
        "version": "new-voice-encryption-modes-0170-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kord-ksp-annotations-jvm/new-voice-encryption-modes-0170-SNAPSHOT/kord-ksp-annotations-jvm-new-voice-encryption-modes-0170-SNAPSHOT.module",
        "group": "dev.kord",
        "module": "kord-ksp-annotations-jvm",
        "version": "new-voice-encryption-modes-0170-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kord-ksp-annotations-jvm/new-voice-encryption-modes-0170-SNAPSHOT/kord-ksp-annotations-jvm-new-voice-encryption-modes-0170-SNAPSHOT.module",
        "group": "dev.kord",
        "module": "kord-ksp-annotations-jvm",
        "version": "new-voice-encryption-modes-0170-SNAPSHOT"
      }
    }
  ]
}
