{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kord-core/new-voice-encryption-modes-0170-SNAPSHOT/kord-core-new-voice-encryption-modes-0170-SNAPSHOT.module",
    "group": "dev.kord",
    "module": "kord-core",
    "version": "new-voice-encryption-modes-0170-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.kord",
          "module": "kord-common",
          "version": {
            "requires": "new-voice-encryption-modes-0170-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-rest",
          "version": {
            "requires": "new-voice-encryption-modes-0170-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-gateway",
          "version": {
            "requires": "new-voice-encryption-modes-0170-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord.cache",
          "module": "cache-api",
          "version": {
            "requires": "0.5.6"
          }
        },
        {
          "group": "dev.kord.cache",
          "module": "cache-map",
          "version": {
            "requires": "0.5.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm.jar",
          "url": "kord-core-jvm-new-voice-encryption-modes-0170-SNAPSHOT.jar",
          "size": 4999176,
          "sha512": "8b24e0647d08894596d81d5953104fbf1bf482284f019ec5be52cb6a876bf59b1c0e7bfe6961516dfb4706e4be09a7c56b2b79f608f568cecf8eb63e39276fae",
          "sha256": "e9a751a7a65a30110d3adfd23b48446a6ad01d9fde2048570b5eebf90d93ebc6",
          "sha1": "1abe8d7b818993c5e47aaadf10f83854a4f2ae5a",
          "md5": "392e992c6993c6d30060ac693d6f3293"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.kord",
          "module": "kord-common",
          "version": {
            "requires": "new-voice-encryption-modes-0170-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-rest",
          "version": {
            "requires": "new-voice-encryption-modes-0170-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-gateway",
          "version": {
            "requires": "new-voice-encryption-modes-0170-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord.cache",
          "module": "cache-api",
          "version": {
            "requires": "0.5.6"
          }
        },
        {
          "group": "dev.kord.cache",
          "module": "cache-map",
          "version": {
            "requires": "0.5.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm.jar",
          "url": "kord-core-jvm-new-voice-encryption-modes-0170-SNAPSHOT.jar",
          "size": 4999176,
          "sha512": "8b24e0647d08894596d81d5953104fbf1bf482284f019ec5be52cb6a876bf59b1c0e7bfe6961516dfb4706e4be09a7c56b2b79f608f568cecf8eb63e39276fae",
          "sha256": "e9a751a7a65a30110d3adfd23b48446a6ad01d9fde2048570b5eebf90d93ebc6",
          "sha1": "1abe8d7b818993c5e47aaadf10f83854a4f2ae5a",
          "md5": "392e992c6993c6d30060ac693d6f3293"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "core-jvm-sources.jar",
          "url": "kord-core-jvm-new-voice-encryption-modes-0170-SNAPSHOT-sources.jar",
          "size": 329975,
          "sha512": "96b39d0244dc31fa5e2802d4239af402bea485cd7dd4d6c5a6f40d450123eeb001697da74c1a1ffbc7fc5e265654c98a9d848e21f58ccafc825d947d6d85d6b6",
          "sha256": "bf5c268aca30611f1d3b2af3c76da14149d61fe9ac0e31af0f14eb7676856c98",
          "sha1": "f097405ec623ea1561bfff9b1f4083ad9ca9d8bd",
          "md5": "2bd873d255c4eaf079167b56ff07230e"
        }
      ]
    }
  ]
}
