{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kord-gateway/0.15.0-SNAPSHOT/kord-gateway-0.15.0-SNAPSHOT.module",
    "group": "dev.kord",
    "module": "kord-gateway",
    "version": "0.15.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.kord",
          "module": "kord-common",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "gateway-jvm.jar",
          "url": "kord-gateway-jvm-0.15.0-SNAPSHOT.jar",
          "size": 585256,
          "sha512": "3522b8cbdfdd071573b34beee480267fbdb89ded73d630338b000572d40539feb2230fb720b9567f9349bf55f91bf075567caa41c6b946b0821d97ed9e146234",
          "sha256": "d6b01ca5f02c2760de6c8bd73badb0b3d2791f660ff84abc07358f310692a041",
          "sha1": "6577ebef50ca28fdf856c20c8a9dffa196e1876a",
          "md5": "9b493c6c754cfd7a433f517acfbe0445"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.kord",
          "module": "kord-common",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "3.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "gateway-jvm.jar",
          "url": "kord-gateway-jvm-0.15.0-SNAPSHOT.jar",
          "size": 585256,
          "sha512": "3522b8cbdfdd071573b34beee480267fbdb89ded73d630338b000572d40539feb2230fb720b9567f9349bf55f91bf075567caa41c6b946b0821d97ed9e146234",
          "sha256": "d6b01ca5f02c2760de6c8bd73badb0b3d2791f660ff84abc07358f310692a041",
          "sha1": "6577ebef50ca28fdf856c20c8a9dffa196e1876a",
          "md5": "9b493c6c754cfd7a433f517acfbe0445"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gateway-jvm-sources.jar",
          "url": "kord-gateway-jvm-0.15.0-SNAPSHOT-sources.jar",
          "size": 37494,
          "sha512": "73b4c349fc99e60fbcf4fecf0e663fe23f035183b4fe8f4624ea46b0a82be1ef2ed7f917f2c2085d8c69218a2074423e1eefda39f9fe972d35714739b85cd988",
          "sha256": "1dc8b7b9258f6169892a33e164bcd530117f74ed1f1ba22b4c827d97ea4c155e",
          "sha1": "445163ab19644acfe62c96cf9f7a73ccc49499cd",
          "md5": "37baa4d25d94b2aeaa7e2d43598d6be3"
        }
      ]
    }
  ]
}
