{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kord-rest/0.15.0-SNAPSHOT/kord-rest-0.15.0-SNAPSHOT.module",
    "group": "dev.kord",
    "module": "kord-rest",
    "version": "0.15.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-common",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "rest-js.klib",
          "url": "kord-rest-js-0.15.0-SNAPSHOT.klib",
          "size": 1101364,
          "sha512": "728ee496f7da3b7ab02c936fa86aab00c32b807970f72b085d5b8e38365b0f9731566ab25fc4562ed7db97e74760961df48fcebedcc0a09eb37e1af96a60c49c",
          "sha256": "e2046ea1723c20a1c2dcb1fe08dbb178c4364c1da9c73061c3e88a4065da32e3",
          "sha1": "cb708f01b6565e2257425267801e880025fcf33a",
          "md5": "f014940282b7b7b719445d609f3db253"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlinx-atomicfu-runtime",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-common",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "rest-js.klib",
          "url": "kord-rest-js-0.15.0-SNAPSHOT.klib",
          "size": 1101364,
          "sha512": "728ee496f7da3b7ab02c936fa86aab00c32b807970f72b085d5b8e38365b0f9731566ab25fc4562ed7db97e74760961df48fcebedcc0a09eb37e1af96a60c49c",
          "sha256": "e2046ea1723c20a1c2dcb1fe08dbb178c4364c1da9c73061c3e88a4065da32e3",
          "sha1": "cb708f01b6565e2257425267801e880025fcf33a",
          "md5": "f014940282b7b7b719445d609f3db253"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "rest-js-sources.jar",
          "url": "kord-rest-js-0.15.0-SNAPSHOT-sources.jar",
          "size": 141071,
          "sha512": "36d3818dd6a51e809d04f61d4d49d514e8b060b0fdfb00da710da8b0a10279f1ebf1e5132e1f5e32c46a4b7d463653328ce574aa1d5521f297cb1dedd014ac1f",
          "sha256": "cd665862d07a38387aa8a1c83ded2f1989d5342c5d38ec81f157f45aceb1951b",
          "sha1": "c0ae317b3f64b805e2d3c77c1ff23566f8fbe59b",
          "md5": "f52a1c81303482d4d12e609dd3fc5241"
        }
      ]
    }
  ]
}
