{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.kord",
    "module": "kord-core-voice",
    "version": "new-voice-encryption-modes-0170-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.kord",
          "module": "kord-core",
          "version": {
            "requires": "new-voice-encryption-modes-0170-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-voice",
          "version": {
            "requires": "new-voice-encryption-modes-0170-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "kord-core-voice-new-voice-encryption-modes-0170-SNAPSHOT.jar",
          "url": "kord-core-voice-new-voice-encryption-modes-0170-SNAPSHOT.jar",
          "size": 4761,
          "sha512": "5858a8adf4627f8b97d381a26c5a56aeb0d05f399291b1962222c6ff3f1d8fe0c27ce90e5c1e24a4546d1f5bd31162b21604665abf1eb2cacb526c93c3b842b1",
          "sha256": "1d7fb255d4be0c33563878afd5ab50e4d3462f902118c545ea360686247aa8c9",
          "sha1": "8c49f60b878910bc9000998d70ebbcea5ca0f7e0",
          "md5": "2e58262b286a59cec7654a0657dd45e4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.kord",
          "module": "kord-core",
          "version": {
            "requires": "new-voice-encryption-modes-0170-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-voice",
          "version": {
            "requires": "new-voice-encryption-modes-0170-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "kord-core-voice-new-voice-encryption-modes-0170-SNAPSHOT.jar",
          "url": "kord-core-voice-new-voice-encryption-modes-0170-SNAPSHOT.jar",
          "size": 4761,
          "sha512": "5858a8adf4627f8b97d381a26c5a56aeb0d05f399291b1962222c6ff3f1d8fe0c27ce90e5c1e24a4546d1f5bd31162b21604665abf1eb2cacb526c93c3b842b1",
          "sha256": "1d7fb255d4be0c33563878afd5ab50e4d3462f902118c545ea360686247aa8c9",
          "sha1": "8c49f60b878910bc9000998d70ebbcea5ca0f7e0",
          "md5": "2e58262b286a59cec7654a0657dd45e4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kord-core-voice-new-voice-encryption-modes-0170-SNAPSHOT-sources.jar",
          "url": "kord-core-voice-new-voice-encryption-modes-0170-SNAPSHOT-sources.jar",
          "size": 882,
          "sha512": "5c6e5a1a057fa0557155baa2857564c4775f132346cf5e2bee46da970fe338dc378d8f3337ca3133a0964ef8b998a5ed400603fca780dd32ab1b71cb8fa447b5",
          "sha256": "e456db95877c4127b3c8f6d7d54cc67267f4daa9242a72b084a77357fdba4da2",
          "sha1": "45d2a4724db5b2a165b287b9faf6eaa024a86167",
          "md5": "0c1be4d47cfd5502cbec711c66142723"
        }
      ]
    }
  ]
}
