{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.kord",
    "module": "kord-gateway",
    "version": "new-voice-encryption-modes-0170-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "dev.kord",
          "module": "kord-common",
          "version": {
            "requires": "new-voice-encryption-modes-0170-SNAPSHOT"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "gateway-metadata.jar",
          "url": "kord-gateway-new-voice-encryption-modes-0170-SNAPSHOT.jar",
          "size": 31506,
          "sha512": "dcd8458b50c816a57a3131e781bf0b53ac019dbecaf73605def14fa2e7e4b8f41d157e10b8619c6c07a8229e60ed0608ae23d62a5bc9e812bac6b4f57f67d91f",
          "sha256": "827eb7be0aa1a0799d588597bd5ce7194cdbfa34d5eff74803c06fa0d8de387d",
          "sha1": "80b16041ef4d2a0d6ba4a5c1ad55915c809f192e",
          "md5": "52a9c4cd2b8dcde92db569b959db3fd7"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "gateway-kotlin-sources.jar",
          "url": "kord-gateway-new-voice-encryption-modes-0170-SNAPSHOT-sources.jar",
          "size": 36213,
          "sha512": "8ef1166b62031867bff805ce8d59b34ba643344ee4b9abbc5a2885613fac0fc3772b41b934d3de73032a8cce89493fe7eb502924a83434553c980b898684127f",
          "sha256": "c5dd921c782a36d5dda22413632d0530a16fdb665a1e333f0399bab478af71c2",
          "sha1": "826225719f86622c0a30c59067893d32b8bc7a02",
          "md5": "c99946980bd8d3c86a0f31fc5f15f8ba"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kord-gateway-js/new-voice-encryption-modes-0170-SNAPSHOT/kord-gateway-js-new-voice-encryption-modes-0170-SNAPSHOT.module",
        "group": "dev.kord",
        "module": "kord-gateway-js",
        "version": "new-voice-encryption-modes-0170-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kord-gateway-js/new-voice-encryption-modes-0170-SNAPSHOT/kord-gateway-js-new-voice-encryption-modes-0170-SNAPSHOT.module",
        "group": "dev.kord",
        "module": "kord-gateway-js",
        "version": "new-voice-encryption-modes-0170-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kord-gateway-js/new-voice-encryption-modes-0170-SNAPSHOT/kord-gateway-js-new-voice-encryption-modes-0170-SNAPSHOT.module",
        "group": "dev.kord",
        "module": "kord-gateway-js",
        "version": "new-voice-encryption-modes-0170-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kord-gateway-jvm/new-voice-encryption-modes-0170-SNAPSHOT/kord-gateway-jvm-new-voice-encryption-modes-0170-SNAPSHOT.module",
        "group": "dev.kord",
        "module": "kord-gateway-jvm",
        "version": "new-voice-encryption-modes-0170-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kord-gateway-jvm/new-voice-encryption-modes-0170-SNAPSHOT/kord-gateway-jvm-new-voice-encryption-modes-0170-SNAPSHOT.module",
        "group": "dev.kord",
        "module": "kord-gateway-jvm",
        "version": "new-voice-encryption-modes-0170-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kord-gateway-jvm/new-voice-encryption-modes-0170-SNAPSHOT/kord-gateway-jvm-new-voice-encryption-modes-0170-SNAPSHOT.module",
        "group": "dev.kord",
        "module": "kord-gateway-jvm",
        "version": "new-voice-encryption-modes-0170-SNAPSHOT"
      }
    }
  ]
}
