{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.kord",
    "module": "kord-core",
    "version": "new-voice-encryption-modes-0170-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "dev.kord",
          "module": "kord-common",
          "version": {
            "requires": "new-voice-encryption-modes-0170-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-rest",
          "version": {
            "requires": "new-voice-encryption-modes-0170-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-gateway",
          "version": {
            "requires": "new-voice-encryption-modes-0170-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord.cache",
          "module": "cache-api",
          "version": {
            "requires": "0.5.6"
          }
        },
        {
          "group": "dev.kord.cache",
          "module": "cache-map",
          "version": {
            "requires": "0.5.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata.jar",
          "url": "kord-core-new-voice-encryption-modes-0170-SNAPSHOT.jar",
          "size": 324415,
          "sha512": "a44eafa1239a169586e202a91df69908565f993c7a865c62b89b971ff13a16a637b8c6babea2a0c719667d69936093948bf24fa59f6350e3aa6b895c933c1f1c",
          "sha256": "7d911df6080f53969525c8cbf36a68595c9d045844a0fdffbd179beccb9e5df8",
          "sha1": "35a6f270098ce260423a42351b8253c026fdae67",
          "md5": "664e46500a8a53e76b7ff51733e3d036"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "core-kotlin-sources.jar",
          "url": "kord-core-new-voice-encryption-modes-0170-SNAPSHOT-sources.jar",
          "size": 328098,
          "sha512": "31ccc4095850bdf2630ec9e0882cafe2a60439e13f41df72b125297c20eaa55380aa892ddcb3f63e844c74e966a73677b1debdf0a63898f8a3714c24b7de7f75",
          "sha256": "1db06775628a31f0ec1131302f26767bd374cf94bd09340919ab7c7fafe03a38",
          "sha1": "294cb03110c0a0f1761e53ba2fa7f4ec2c1225c1",
          "md5": "5f71c6dcfed469bec1667a69f0a9e8aa"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kord-core-js/new-voice-encryption-modes-0170-SNAPSHOT/kord-core-js-new-voice-encryption-modes-0170-SNAPSHOT.module",
        "group": "dev.kord",
        "module": "kord-core-js",
        "version": "new-voice-encryption-modes-0170-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kord-core-js/new-voice-encryption-modes-0170-SNAPSHOT/kord-core-js-new-voice-encryption-modes-0170-SNAPSHOT.module",
        "group": "dev.kord",
        "module": "kord-core-js",
        "version": "new-voice-encryption-modes-0170-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kord-core-js/new-voice-encryption-modes-0170-SNAPSHOT/kord-core-js-new-voice-encryption-modes-0170-SNAPSHOT.module",
        "group": "dev.kord",
        "module": "kord-core-js",
        "version": "new-voice-encryption-modes-0170-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kord-core-jvm/new-voice-encryption-modes-0170-SNAPSHOT/kord-core-jvm-new-voice-encryption-modes-0170-SNAPSHOT.module",
        "group": "dev.kord",
        "module": "kord-core-jvm",
        "version": "new-voice-encryption-modes-0170-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kord-core-jvm/new-voice-encryption-modes-0170-SNAPSHOT/kord-core-jvm-new-voice-encryption-modes-0170-SNAPSHOT.module",
        "group": "dev.kord",
        "module": "kord-core-jvm",
        "version": "new-voice-encryption-modes-0170-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kord-core-jvm/new-voice-encryption-modes-0170-SNAPSHOT/kord-core-jvm-new-voice-encryption-modes-0170-SNAPSHOT.module",
        "group": "dev.kord",
        "module": "kord-core-jvm",
        "version": "new-voice-encryption-modes-0170-SNAPSHOT"
      }
    }
  ]
}
