{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kord-rest/0.15.0-SNAPSHOT/kord-rest-0.15.0-SNAPSHOT.module",
    "group": "dev.kord",
    "module": "kord-rest",
    "version": "0.15.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.kord",
          "module": "kord-common",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "rest-jvm.jar",
          "url": "kord-rest-jvm-0.15.0-SNAPSHOT.jar",
          "size": 2255878,
          "sha512": "402f1a323ed6fca61d95fac0a6384bf726f65b5a241f26e4292d190256f7c5e1d9bdcbe3c399da79dfaa1e9c6cde088e835c75675ad4eba0232fd0c454a91a09",
          "sha256": "b387174ccc75bdf8ef964c595f3e7474f0364f88750421e9f8ba5338f0eb8d95",
          "sha1": "36d10dd8bc07fbcc633ae42522a829f3972c19cb",
          "md5": "c706685cbd0955b5f57042a25e76e95d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.kord",
          "module": "kord-common",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "rest-jvm.jar",
          "url": "kord-rest-jvm-0.15.0-SNAPSHOT.jar",
          "size": 2255878,
          "sha512": "402f1a323ed6fca61d95fac0a6384bf726f65b5a241f26e4292d190256f7c5e1d9bdcbe3c399da79dfaa1e9c6cde088e835c75675ad4eba0232fd0c454a91a09",
          "sha256": "b387174ccc75bdf8ef964c595f3e7474f0364f88750421e9f8ba5338f0eb8d95",
          "sha1": "36d10dd8bc07fbcc633ae42522a829f3972c19cb",
          "md5": "c706685cbd0955b5f57042a25e76e95d"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "rest-jvm-sources.jar",
          "url": "kord-rest-jvm-0.15.0-SNAPSHOT-sources.jar",
          "size": 142640,
          "sha512": "56b2a1c51a5524bbddba1f061a098217b3f5491806473de81fd70f1225681418b669079273090dcc87cafac87cc5e51728c775098ae3972cb908b3cd88369fd6",
          "sha256": "f66bdb49b5a67b70b0347b4381bedc2309cdac133a647b0286543133fd5f91ec",
          "sha1": "c390e7101e27a9e93edef91829dc368a6427c889",
          "md5": "10ffcc770bc8f956cba0ae7977c34e85"
        }
      ]
    }
  ]
}
