{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kord-gateway/new-voice-encryption-modes-0170-SNAPSHOT/kord-gateway-new-voice-encryption-modes-0170-SNAPSHOT.module",
    "group": "dev.kord",
    "module": "kord-gateway",
    "version": "new-voice-encryption-modes-0170-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.29.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-common",
          "version": {
            "requires": "new-voice-encryption-modes-0170-SNAPSHOT"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "gateway-js.klib",
          "url": "kord-gateway-js-new-voice-encryption-modes-0170-SNAPSHOT.klib",
          "size": 293969,
          "sha512": "1642ae01b8b6c4aa23b392c43d8edd86cc10fab8e93fb4e7d9f5d61cfbea9953263919f7ec161491af7c506f8a36ac15036804bcc5c983994b244be4ff862b7a",
          "sha256": "fe0e545dc97af2b86068157d7e833e327c0f7670d7c708bf2cbc09329e5c6066",
          "sha1": "79a6304faeeee339c1ae99fc9583ed9f2e37fc9a",
          "md5": "67dd1901183b9ac8ead65b812c036e36"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlinx-atomicfu-runtime",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.29.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-common",
          "version": {
            "requires": "new-voice-encryption-modes-0170-SNAPSHOT"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-node",
          "version": {
            "requires": "2025.7.14-22.13.10"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-ksp-annotations",
          "version": {
            "requires": "new-voice-encryption-modes-0170-SNAPSHOT"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "gateway-js.klib",
          "url": "kord-gateway-js-new-voice-encryption-modes-0170-SNAPSHOT.klib",
          "size": 293969,
          "sha512": "1642ae01b8b6c4aa23b392c43d8edd86cc10fab8e93fb4e7d9f5d61cfbea9953263919f7ec161491af7c506f8a36ac15036804bcc5c983994b244be4ff862b7a",
          "sha256": "fe0e545dc97af2b86068157d7e833e327c0f7670d7c708bf2cbc09329e5c6066",
          "sha1": "79a6304faeeee339c1ae99fc9583ed9f2e37fc9a",
          "md5": "67dd1901183b9ac8ead65b812c036e36"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "gateway-js-sources.jar",
          "url": "kord-gateway-js-new-voice-encryption-modes-0170-SNAPSHOT-sources.jar",
          "size": 37376,
          "sha512": "32fb9e3342456298033bf1b484d8c3eaa9fc0ec7f677048c8f2f4dcaf8bcb1a681198ddf7900cb6d583774593d8962649ceba600db6a9d231eea03a911c9fe97",
          "sha256": "761274cdbbd8bfd8a9b96093eb16dfa6c59d01c1c14f2171b692f4cd7a7f612b",
          "sha1": "33ae1e683922beecd03751dfd9f567b1d442b893",
          "md5": "b7d7485eccd83ff42cbfc422a84eed07"
        }
      ]
    }
  ]
}
