{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kord-common/new-voice-encryption-modes-SNAPSHOT/kord-common-new-voice-encryption-modes-SNAPSHOT.module",
    "group": "dev.kord",
    "module": "kord-common",
    "version": "new-voice-encryption-modes-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-js",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "common-js.klib",
          "url": "kord-common-js-new-voice-encryption-modes-SNAPSHOT.klib",
          "size": 1198880,
          "sha512": "d967eafbf12b8e9738f3845db967eff9861cf92ca3bbb9bcebc2deedded1f83af1915f0886615997a149141fae27b5b67a34e1db0a6fb8e9d49f140309d473c3",
          "sha256": "a48af748de54d4d156cdfa58c702d85b7e798f8b870bc9c67bd95c101a15032d",
          "sha1": "7b6ef264b270194cfe08e6d93a0ad00aa17b5165",
          "md5": "d34758e228f2ec746ca42fc844498543"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlinx-atomicfu-runtime",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-js",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-ksp-annotations",
          "version": {
            "requires": "new-voice-encryption-modes-SNAPSHOT"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.3.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrent-collections",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-js.klib",
          "url": "kord-common-js-new-voice-encryption-modes-SNAPSHOT.klib",
          "size": 1198880,
          "sha512": "d967eafbf12b8e9738f3845db967eff9861cf92ca3bbb9bcebc2deedded1f83af1915f0886615997a149141fae27b5b67a34e1db0a6fb8e9d49f140309d473c3",
          "sha256": "a48af748de54d4d156cdfa58c702d85b7e798f8b870bc9c67bd95c101a15032d",
          "sha1": "7b6ef264b270194cfe08e6d93a0ad00aa17b5165",
          "md5": "d34758e228f2ec746ca42fc844498543"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "common-js-sources.jar",
          "url": "kord-common-js-new-voice-encryption-modes-SNAPSHOT-sources.jar",
          "size": 192047,
          "sha512": "92ca00635cd12b816bec5f9ca18697106a19088a1f298171831f81558678c3abe52f9a5542de1f19063a62786a5dc3d93457d907f71a58cac0746848533b7b21",
          "sha256": "85c8602ce5f015008d254b581599d85c665f14631a7beaf71eb316680b2e7e68",
          "sha1": "be0119b7a294c64ddc218584e3315b10b2865316",
          "md5": "398b7dfa77516f8a1f3979e8bf18a6f6"
        }
      ]
    }
  ]
}
