{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.kord",
    "module": "kord-gateway",
    "version": "0.15.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "dev.kord",
          "module": "kord-common",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "gateway-metadata.jar",
          "url": "kord-gateway-0.15.0-SNAPSHOT.jar",
          "size": 32212,
          "sha512": "fd5a926a41ec98612acfbc86e3c54bfa4b71252851220a119dc93fec262613f64021fd6e4396196d8b5e752e2478855060995e8263d6743262e79415220d602d",
          "sha256": "f607de515657fc467ad05f477b82818de7abe5dc99f56603d09e1977cc63c3a3",
          "sha1": "deb854838945b69c174094ed848c4e6b8fce4b52",
          "md5": "2a35c78cdbd7942e24428cc07e2ed2c0"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "gateway-kotlin-sources.jar",
          "url": "kord-gateway-0.15.0-SNAPSHOT-sources.jar",
          "size": 36732,
          "sha512": "898000a3f4241eb75dd9dca5b91a42dd04db5adfae1f196c58d5bb7741489c2359d7742bc2c1b2e7514ec4691b034911643a5a6bbb157fe9cd42359e1fd0a655",
          "sha256": "6c8081e288982ddfd12e36030943719461b70859913758b89d3f7a25bf561485",
          "sha1": "8e667307245f997bca7c8117c5146b53ca42538b",
          "md5": "9a32c53775b83a281d0745633a1770cf"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kord-gateway-js/0.15.0-SNAPSHOT/kord-gateway-js-0.15.0-SNAPSHOT.module",
        "group": "dev.kord",
        "module": "kord-gateway-js",
        "version": "0.15.0-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kord-gateway-js/0.15.0-SNAPSHOT/kord-gateway-js-0.15.0-SNAPSHOT.module",
        "group": "dev.kord",
        "module": "kord-gateway-js",
        "version": "0.15.0-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kord-gateway-js/0.15.0-SNAPSHOT/kord-gateway-js-0.15.0-SNAPSHOT.module",
        "group": "dev.kord",
        "module": "kord-gateway-js",
        "version": "0.15.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kord-gateway-jvm/0.15.0-SNAPSHOT/kord-gateway-jvm-0.15.0-SNAPSHOT.module",
        "group": "dev.kord",
        "module": "kord-gateway-jvm",
        "version": "0.15.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kord-gateway-jvm/0.15.0-SNAPSHOT/kord-gateway-jvm-0.15.0-SNAPSHOT.module",
        "group": "dev.kord",
        "module": "kord-gateway-jvm",
        "version": "0.15.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kord-gateway-jvm/0.15.0-SNAPSHOT/kord-gateway-jvm-0.15.0-SNAPSHOT.module",
        "group": "dev.kord",
        "module": "kord-gateway-jvm",
        "version": "0.15.0-SNAPSHOT"
      }
    }
  ]
}
