{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kord-ksp-annotations/new-voice-encryption-modes-0170-SNAPSHOT/kord-ksp-annotations-new-voice-encryption-modes-0170-SNAPSHOT.module",
    "group": "dev.kord",
    "module": "kord-ksp-annotations",
    "version": "new-voice-encryption-modes-0170-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "ksp-annotations-js.klib",
          "url": "kord-ksp-annotations-js-new-voice-encryption-modes-0170-SNAPSHOT.klib",
          "size": 7948,
          "sha512": "4089f98413db919546e1aaa544e2e46f608e0a3e02ad358c88f03fbc97828ec3fdd838863a15bb4a1d1bd3c3de6d687525c71bde97d072694ef3235befacc632",
          "sha256": "4b36015d9c56e04a43a861ad02fac80415aebc4b30acc7fd98a080c74f4bfadb",
          "sha1": "0e5f2ec3737d983646b989a77f205f6a203345ee",
          "md5": "a9eba5fb04c95eca999ea15d58bcb552"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "ksp-annotations-js.klib",
          "url": "kord-ksp-annotations-js-new-voice-encryption-modes-0170-SNAPSHOT.klib",
          "size": 7948,
          "sha512": "4089f98413db919546e1aaa544e2e46f608e0a3e02ad358c88f03fbc97828ec3fdd838863a15bb4a1d1bd3c3de6d687525c71bde97d072694ef3235befacc632",
          "sha256": "4b36015d9c56e04a43a861ad02fac80415aebc4b30acc7fd98a080c74f4bfadb",
          "sha1": "0e5f2ec3737d983646b989a77f205f6a203345ee",
          "md5": "a9eba5fb04c95eca999ea15d58bcb552"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "ksp-annotations-js-sources.jar",
          "url": "kord-ksp-annotations-js-new-voice-encryption-modes-0170-SNAPSHOT-sources.jar",
          "size": 1200,
          "sha512": "34642383e14d027a42da882a85e02f0ac6742b49dc4b290389f9ef6840dc72c69b472e5a624d2a465f84b36c96665d676dbdfc04a4b7ca4d1085f7a1affdfe0b",
          "sha256": "0c176462e51edf8ae8369e6db0f2d2b3c9dcbe1eb1a5f98e6433b3674e4a9daa",
          "sha1": "2fdf65336269ad40e4bc74778b6d8fbdc558326a",
          "md5": "c098039c227b6feb99a7cd3434b7eacf"
        }
      ]
    }
  ]
}
