{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kord-common/new-voice-encryption-modes-0170-SNAPSHOT/kord-common-new-voice-encryption-modes-0170-SNAPSHOT.module",
    "group": "dev.kord",
    "module": "kord-common",
    "version": "new-voice-encryption-modes-0170-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-js",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.29.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "common-js.klib",
          "url": "kord-common-js-new-voice-encryption-modes-0170-SNAPSHOT.klib",
          "size": 1204668,
          "sha512": "0d5e23fd318ebae7bc4ecb3dedc24dc94302086cb3a3c86f210c13444890294baab503f9daa44f771637381e5b2d53614dad162a7032816892e39aafed97761c",
          "sha256": "614121a630beb5ce2d24992e70dfec003d111d0fbd94178a92879b35196e4695",
          "sha1": "ea936ed1d575dc3a18b99e520e14b56e244137e6",
          "md5": "3366c0bdc207efb9064195bba90c3e5a"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlinx-atomicfu-runtime",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-js",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.29.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-ksp-annotations",
          "version": {
            "requires": "new-voice-encryption-modes-0170-SNAPSHOT"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.3.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrent-collections",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-js.klib",
          "url": "kord-common-js-new-voice-encryption-modes-0170-SNAPSHOT.klib",
          "size": 1204668,
          "sha512": "0d5e23fd318ebae7bc4ecb3dedc24dc94302086cb3a3c86f210c13444890294baab503f9daa44f771637381e5b2d53614dad162a7032816892e39aafed97761c",
          "sha256": "614121a630beb5ce2d24992e70dfec003d111d0fbd94178a92879b35196e4695",
          "sha1": "ea936ed1d575dc3a18b99e520e14b56e244137e6",
          "md5": "3366c0bdc207efb9064195bba90c3e5a"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "common-js-sources.jar",
          "url": "kord-common-js-new-voice-encryption-modes-0170-SNAPSHOT-sources.jar",
          "size": 191779,
          "sha512": "50f4aa092fe8d0a052dffe99a2aa72ebe59503faf58beafeec0e3c33d170874576d36e6a6c00e946d7d96a7ec9951a8e197ed2367e25f8e5def58b77e6d7d08d",
          "sha256": "7a13f232f782b83f9dd6feb59b2511756fa254b29f10c4436332f112e6bfde86",
          "sha1": "64a120276641769bfabf58f9423c026bd9fdb95c",
          "md5": "32ddd24bfa77b0b4041bd2ffc45e059e"
        }
      ]
    }
  ]
}
