{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kord-rest/new-voice-encryption-modes-0170-SNAPSHOT/kord-rest-new-voice-encryption-modes-0170-SNAPSHOT.module",
    "group": "dev.kord",
    "module": "kord-rest",
    "version": "new-voice-encryption-modes-0170-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.kord",
          "module": "kord-common",
          "version": {
            "requires": "new-voice-encryption-modes-0170-SNAPSHOT"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "rest-jvm.jar",
          "url": "kord-rest-jvm-new-voice-encryption-modes-0170-SNAPSHOT.jar",
          "size": 2375652,
          "sha512": "111f7b719305ad5946947db66c3e8adbc132ffcb7a8abd4d8043e4197238304706154d8730503a8cb269243cbfa12a67f0c6f99a103642d1a0dc2e5ba382b4ac",
          "sha256": "328e5a7b25b4a40bb6e78720720eb1a12552f2575932c423c8593e3d019e6c85",
          "sha1": "25a2671befa2554063ebe133d86dea1f41adad0f",
          "md5": "f8040345236c7b83c074a638ff4dbcdb"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.kord",
          "module": "kord-common",
          "version": {
            "requires": "new-voice-encryption-modes-0170-SNAPSHOT"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "rest-jvm.jar",
          "url": "kord-rest-jvm-new-voice-encryption-modes-0170-SNAPSHOT.jar",
          "size": 2375652,
          "sha512": "111f7b719305ad5946947db66c3e8adbc132ffcb7a8abd4d8043e4197238304706154d8730503a8cb269243cbfa12a67f0c6f99a103642d1a0dc2e5ba382b4ac",
          "sha256": "328e5a7b25b4a40bb6e78720720eb1a12552f2575932c423c8593e3d019e6c85",
          "sha1": "25a2671befa2554063ebe133d86dea1f41adad0f",
          "md5": "f8040345236c7b83c074a638ff4dbcdb"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "rest-jvm-sources.jar",
          "url": "kord-rest-jvm-new-voice-encryption-modes-0170-SNAPSHOT-sources.jar",
          "size": 155826,
          "sha512": "822eab8255ad88d3d40c527ff4e5dc62f6a226c20faa3d592090421863aeea1e531e237b8982d0a8bd772b9bca8924ba6e1147718fe0c24cd5dd131a3224bc4e",
          "sha256": "4c4b83003101831d2c4912436a80a55238ae38a6d2713b3909fb00681d949aa8",
          "sha1": "a643401c97aba88e9d63979dbf9f269669a51777",
          "md5": "d5026b2ba0765a4944c5de68a876863b"
        }
      ]
    }
  ]
}
