{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.kord",
    "module": "kord-bom",
    "version": "0.15.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "dev.kord",
          "module": "kord-common-js",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-common-jvm",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-common",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-core-js",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-core-jvm",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-core",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-core-voice",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-gateway-js",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-gateway-jvm",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-gateway",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-ksp-annotations-js",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-ksp-annotations-jvm",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-ksp-annotations",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-rest-js",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-rest-jvm",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-rest",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-voice",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "dev.kord",
          "module": "kord-common-js",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-common-jvm",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-common",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-core-js",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-core-jvm",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-core",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-core-voice",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-gateway-js",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-gateway-jvm",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-gateway",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-ksp-annotations-js",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-ksp-annotations-jvm",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-ksp-annotations",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-rest-js",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-rest-jvm",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-rest",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-voice",
          "version": {
            "requires": "0.15.0-SNAPSHOT"
          }
        }
      ]
    }
  ]
}
