{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kord-core/new-voice-encryption-modes-0170-SNAPSHOT/kord-core-new-voice-encryption-modes-0170-SNAPSHOT.module",
    "group": "dev.kord",
    "module": "kord-core",
    "version": "new-voice-encryption-modes-0170-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.29.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-common",
          "version": {
            "requires": "new-voice-encryption-modes-0170-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-rest",
          "version": {
            "requires": "new-voice-encryption-modes-0170-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-gateway",
          "version": {
            "requires": "new-voice-encryption-modes-0170-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord.cache",
          "module": "cache-api",
          "version": {
            "requires": "0.5.6"
          }
        },
        {
          "group": "dev.kord.cache",
          "module": "cache-map",
          "version": {
            "requires": "0.5.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-js.klib",
          "url": "kord-core-js-new-voice-encryption-modes-0170-SNAPSHOT.klib",
          "size": 1934516,
          "sha512": "1a5536f339d405afcc5ee0dec0e4205614f757d33d9f31cb4b6ef9a3bf7f2e0a5427e94768a3ffe9130dbb8d69b3c77b2e4dd8a1f8a5e151be1dbe4e8cd73286",
          "sha256": "da5ac1fad8f0163ec7cb137ccc242901e82957cf79e1fc2bbbf2dd0a655d335c",
          "sha1": "9dfb6c7e717496fb89d1a7265f7b74ace116341a",
          "md5": "5ccc0b91df846b0df667694b32727f75"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlinx-atomicfu-runtime",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.29.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-common",
          "version": {
            "requires": "new-voice-encryption-modes-0170-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-rest",
          "version": {
            "requires": "new-voice-encryption-modes-0170-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-gateway",
          "version": {
            "requires": "new-voice-encryption-modes-0170-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord.cache",
          "module": "cache-api",
          "version": {
            "requires": "0.5.6"
          }
        },
        {
          "group": "dev.kord.cache",
          "module": "cache-map",
          "version": {
            "requires": "0.5.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "core-js.klib",
          "url": "kord-core-js-new-voice-encryption-modes-0170-SNAPSHOT.klib",
          "size": 1934516,
          "sha512": "1a5536f339d405afcc5ee0dec0e4205614f757d33d9f31cb4b6ef9a3bf7f2e0a5427e94768a3ffe9130dbb8d69b3c77b2e4dd8a1f8a5e151be1dbe4e8cd73286",
          "sha256": "da5ac1fad8f0163ec7cb137ccc242901e82957cf79e1fc2bbbf2dd0a655d335c",
          "sha1": "9dfb6c7e717496fb89d1a7265f7b74ace116341a",
          "md5": "5ccc0b91df846b0df667694b32727f75"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "core-js-sources.jar",
          "url": "kord-core-js-new-voice-encryption-modes-0170-SNAPSHOT-sources.jar",
          "size": 328401,
          "sha512": "6f92e05064b428e27e094c7194f0fe6da5eb6a069165c22e965a777787124b2d5c8e9f8dc631ba326bc1a2a25e3b9d0b1afb0a1f740b1ca494dfa90136b4c92e",
          "sha256": "475597598a20640986ca42cd121514d09807c1f0f1b5eb44fe4e35e52461cada",
          "sha1": "3a9850e5cd6b24e37ccbea49b26f091de10097b2",
          "md5": "bdadd5abbeb4a8824202263bce08fd04"
        }
      ]
    }
  ]
}
