{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kord-gateway/new-voice-encryption-modes-SNAPSHOT/kord-gateway-new-voice-encryption-modes-SNAPSHOT.module",
    "group": "dev.kord",
    "module": "kord-gateway",
    "version": "new-voice-encryption-modes-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.kord",
          "module": "kord-common",
          "version": {
            "requires": "new-voice-encryption-modes-SNAPSHOT"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "gateway-jvm.jar",
          "url": "kord-gateway-jvm-new-voice-encryption-modes-SNAPSHOT.jar",
          "size": 583749,
          "sha512": "ed7b494965f7679baaf4b426a88e9a869c49af16ceb097cd5f97d5d21074f3fc832ec684eb7a02a42c2006aab1e56d0f7921486660eb6fb627d0bf9b8128a350",
          "sha256": "4d955ad91c3b99310da164a0de9db943a854b51c211e586a324fffdf52bc9c9c",
          "sha1": "8d178a5fa90392c707ec9c02cff4cb856404d5ef",
          "md5": "c8b74767a46b0fa7c64586b0a1529b80"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.kord",
          "module": "kord-common",
          "version": {
            "requires": "new-voice-encryption-modes-SNAPSHOT"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "gateway-jvm.jar",
          "url": "kord-gateway-jvm-new-voice-encryption-modes-SNAPSHOT.jar",
          "size": 583749,
          "sha512": "ed7b494965f7679baaf4b426a88e9a869c49af16ceb097cd5f97d5d21074f3fc832ec684eb7a02a42c2006aab1e56d0f7921486660eb6fb627d0bf9b8128a350",
          "sha256": "4d955ad91c3b99310da164a0de9db943a854b51c211e586a324fffdf52bc9c9c",
          "sha1": "8d178a5fa90392c707ec9c02cff4cb856404d5ef",
          "md5": "c8b74767a46b0fa7c64586b0a1529b80"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gateway-jvm-sources.jar",
          "url": "kord-gateway-jvm-new-voice-encryption-modes-SNAPSHOT-sources.jar",
          "size": 37280,
          "sha512": "bc82eb4d3d665f9ae138e50ee6af9a7081992e67e383f6ef3b010785c2e1ca35f3eea58fd50fd3e9d4e5358288593cb7d3008c9f62bf8c4b11550e26f7d2dd94",
          "sha256": "e5cb5c3be25dd9be1cab9895227cc2fe5162c3ae32e117fed4b3c990734b7458",
          "sha1": "cc8fe382ab2f765e3cd90b9693800cba1ca94f06",
          "md5": "a5437a7a9da772352134a96a27ef168c"
        }
      ]
    }
  ]
}
