{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.kord",
    "module": "kord-voice",
    "version": "new-voice-encryption-modes-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.kord",
          "module": "kord-common",
          "version": {
            "requires": "new-voice-encryption-modes-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-gateway",
          "version": {
            "requires": "new-voice-encryption-modes-SNAPSHOT"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "kord-voice-new-voice-encryption-modes-SNAPSHOT.jar",
          "url": "kord-voice-new-voice-encryption-modes-SNAPSHOT.jar",
          "size": 668473,
          "sha512": "17a3c6260754a9cff74d4ac93d7dacafc996984890d6ee0e494ae84e65e732df28b539c3da8403cfbaf6532a883e6685f65845293d9ee25eafa84edaa0a5c89e",
          "sha256": "fde3a1e63d01938db5582706c34a56a96ee970f7cf850ecba1609bb45192bc74",
          "sha1": "022c04eeaf90cb70865d3b959696500fbe22313f",
          "md5": "5ca567ef7b5cb09de3a37644e309bd93"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-common",
          "version": {
            "requires": "new-voice-encryption-modes-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-gateway",
          "version": {
            "requires": "new-voice-encryption-modes-SNAPSHOT"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "kord-voice-new-voice-encryption-modes-SNAPSHOT.jar",
          "url": "kord-voice-new-voice-encryption-modes-SNAPSHOT.jar",
          "size": 668473,
          "sha512": "17a3c6260754a9cff74d4ac93d7dacafc996984890d6ee0e494ae84e65e732df28b539c3da8403cfbaf6532a883e6685f65845293d9ee25eafa84edaa0a5c89e",
          "sha256": "fde3a1e63d01938db5582706c34a56a96ee970f7cf850ecba1609bb45192bc74",
          "sha1": "022c04eeaf90cb70865d3b959696500fbe22313f",
          "md5": "5ca567ef7b5cb09de3a37644e309bd93"
        }
      ]
    }
  ]
}
