{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.kord",
    "module": "kord-voice",
    "version": "new-voice-encryption-modes-0170-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.kord",
          "module": "kord-common",
          "version": {
            "requires": "new-voice-encryption-modes-0170-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-gateway",
          "version": {
            "requires": "new-voice-encryption-modes-0170-SNAPSHOT"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "kord-voice-new-voice-encryption-modes-0170-SNAPSHOT.jar",
          "url": "kord-voice-new-voice-encryption-modes-0170-SNAPSHOT.jar",
          "size": 681669,
          "sha512": "758f302a91b5b0a8a92e2514195708ef11c9970cd272f6615e357835b3d39ac16dbc67b0136fda3d129c2476b37d0eeb6b9c4f1dfb7186f7b54aca2a9c9fa100",
          "sha256": "b667809ddf03ae96171ced5d74b104d192b8e94752fc5b631f6fc22b5c536d0b",
          "sha1": "59ee1b3bccd926fd3fc574e50f78781521c8003a",
          "md5": "c067785778092501ebdca61dc2abfd65"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.13"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-common",
          "version": {
            "requires": "new-voice-encryption-modes-0170-SNAPSHOT"
          }
        },
        {
          "group": "dev.kord",
          "module": "kord-gateway",
          "version": {
            "requires": "new-voice-encryption-modes-0170-SNAPSHOT"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "kord-voice-new-voice-encryption-modes-0170-SNAPSHOT.jar",
          "url": "kord-voice-new-voice-encryption-modes-0170-SNAPSHOT.jar",
          "size": 681669,
          "sha512": "758f302a91b5b0a8a92e2514195708ef11c9970cd272f6615e357835b3d39ac16dbc67b0136fda3d129c2476b37d0eeb6b9c4f1dfb7186f7b54aca2a9c9fa100",
          "sha256": "b667809ddf03ae96171ced5d74b104d192b8e94752fc5b631f6fc22b5c536d0b",
          "sha1": "59ee1b3bccd926fd3fc574e50f78781521c8003a",
          "md5": "c067785778092501ebdca61dc2abfd65"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kord-voice-new-voice-encryption-modes-0170-SNAPSHOT-sources.jar",
          "url": "kord-voice-new-voice-encryption-modes-0170-SNAPSHOT-sources.jar",
          "size": 74102,
          "sha512": "31c6f7ba22434fbc0239023860881e201e371a3cff9c442821c6b7656d1dc7dcf2c1d998e073101a87abe092cf21463ff1d224976685988f03521a25e564c4b4",
          "sha256": "a59f4bbb6f45263cc2e230321faf77ee7d6e6294f09092c739a4681ff1dcd5f4",
          "sha1": "ff5c1c7ac33e59e20b4c83c783b4ff44f3d5f1c9",
          "md5": "cf6bf94ca5c140f9daa0117b48c50efc"
        }
      ]
    }
  ]
}
