name: Create Repo - Maven project

on:
  workflow_dispatch:
    inputs:
      github-repo:
        description: 'GitHub repository name (e.g, jaoafa/MyMaid4)'
        required: true
      jdk-version:
        description: 'JDK version'
        required: true
        default: '16'

jobs:
  add-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ${{ github.event.inputs.github-repo }}
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.github-repo }}
          path: project

      - name: Checkout tomacheese/repo.tomacheese.com
        uses: actions/checkout@v4
        with:
          path: repositorys

      - name: Set up JDK ${{ github.event.inputs.jdk-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ github.event.inputs.jdk-version }}

      - name: Maven deploy
        working-directory: ./project/
        run: |
          pwd
          ls -la
          mvn deploy -DaltDeploymentRepository=internal.repo::default::file:///${{ github.workspace }}/repositorys/

      - name: List directory
        run: |
          sudo apt install -y tree
          tree -L 5 .

      - name: Set git config
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: 'github-repo string "/" replace to "-"'
        uses: mad9000/actions-find-and-replace-string@5
        id: github-repo
        with:
          source: ${{ github.event.inputs.github-repo }}
          find: '/'
          replace: '-'

      - name: Create pull request
        working-directory: ./repositorys/
        run: |
          pwd
          git status
          git status | grep -e modified -e "Untracked files" && hub add -A && \
            hub commit -m "feat: ${{ github.event.inputs.github-repo }}" && \
            hub push --set-upstream origin HEAD:add-repo-${{ steps.github-repo.outputs.value }} && \
            hub pull-request -p -h add-repo-${{ steps.github-repo.outputs.value }} -b master -m "feat: Add repo ${{ github.event.inputs.github-repo }}" -r book000 -f || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
