name: Generate readme

on:
  push:
    branches:
     - master

jobs:
  generate:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup node env
      uses: actions/setup-node@v2.4.1
      with:
        node-version: 16

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      working-directory: ./.github/generate-readme/
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Cache node_modules
      uses: actions/cache@v2.1.6
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      working-directory: ./.github/generate-readme/
      run: yarn

    - name: Generate README file
      working-directory: ./.github/generate-readme/
      run: yarn build --target ../../ --output ../../README.md

    - name: Commit & Push
      run: |
        git status | grep modified && git add README.md && git commit -v -m "feat: Updated README.md [skip ci]" && git push
