name: Update repo - jao Super Achievements2

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'jSA2 version'
        required: true

jobs:
  update-jsa2-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: jaoafa/jaoSuperAchievement2
          path: project

      - name: Checkout tomacheese/repo.tomacheese.com
        uses: actions/checkout@v4
        with:
          path: repositorys

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: Sed Version
        working-directory: ./project/
        run: |
          sed -r -i "1,/version/s#<version>(.+?)</version>#<version>${{ github.event.inputs.version }}</version>#" pom.xml
          git diff

      - name: Maven deploy
        working-directory: ./project/
        run: |
          pwd
          ls -la
          mvn deploy -DaltDeploymentRepository=internal.repo::default::file:///${{ github.workspace }}/repositorys/

      - name: List directory
        run: |
          sudo apt install -y tree
          tree -L 5 .

      - name: Set git config
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create pull request
        working-directory: ./repositorys/
        run: |
          pwd
          git status
          git status | grep -e modified -e "Untracked files" && hub add -A && \
            hub commit -m "feat: Update repo jao Super Achievement2 ${{ github.event.inputs.version }}" && \
            hub push --set-upstream origin HEAD:update-repo-jsa2-${{ github.event.inputs.version }} && \
            hub pull-request -p -h update-repo-jsa2-${{ github.event.inputs.version }} -b master -m "feat: Update repo jao Super Achievement2 ${{ github.event.inputs.version }}" -r book000 -f || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
